### PR TITLE
support custom build format

### PR DESCRIPTION
**Pull request by 0b11001111**
Hey, as the title says I was missing an option to specify the output format for poetry's build command so I added it.

Thanks for making this action!

### CODE REVIEW

**Comment by JRubics** [comment]
Thank you!! :D

**Review by JRubics — APPROVED** [review]

**Comment by 0b11001111** [comment]
:)

**Comment by 0b11001111** [comment]
Uuh, would you mind to add a respective release?

**Comment by JRubics** [comment]
Done :)

**Pull request merged**
